### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by emmatyping** [IronManMark20/pyhooked#11]
Once 0.8 is out the door (hopefully today or tomorrow), we can start updating the wiki to cover the new syntax of the library.

**Comment by na-fis** [comment]
Hi @ethanhs ! From your code, it seems like mouse hooks should be working now (It is marked as future works now). I just need to detect if there is any kind of activity from keyboard and mouse. Seems like your code is just perfect!

Thanks a lot.

**Comment by emmatyping** [comment]
Yes, That is correct. You should be able to do something like:

```
def handle_events(args):
    if isinstance(args, MouseEvent):
        if args.mouse_x == 300 and args.mouse_y == 400:
            print("Mouse is at (300,400") 
```

Glad you found the library useful. It was originally something that I just hacked together for my own use, but I realized others may want to use it too. :)

**Comment by msouder** [comment]
What's a graceful way to stop the hook process?  Now I call hk.hook in a daemon thread so it closes out out when my main program exits.  Is there a proper way to do this?

**Comment by emmatyping** [comment]
@msouder are you asking how to stop the thread? Threads stop when their loops terminate. Perhaps you could give an example of how you are using it?

**Comment by msouder** [comment]
Sorry if this is ridiculously obvious.  Beginner at this type of thing.

Below is how I'm currently using it.  When I send the stop command, the main loop exits and the hotkey thread dies.  This is the behavior I want, I just think there is a proper way to do this that I just don't know.

```
import threading
from pyhooked import Hook, KeyboardEvent
import logging
import time

logging.basicConfig(level=logging.DEBUG,
                    format='[%(levelname)s] (%(threadName)-10s) %(message)s',
                    )

# Setup stop event
stop = threading.Event()

# Setup hot key handler
def handle_hotkeys(args, e=stop):
    if isinstance(args, KeyboardEvent):
        logging.debug(args.key_code)
        if args.current_key == 'F1' and \
                        args.event_type == 'key down' and \
                        'Lcontrol' in args.pressed_key:
            logging.debug("Ctrl + F1 was pressed, stopping")
            e.set()

# Start hot key thread
hk = Hook()
hk.handler = lambda x: handle_hotkeys(x, stop)
hk_thread = threading.Thread(name='hotkey', target=hk.hook,
                             daemon=True)
hk_thread.start()

# Main loop
while not stop.is_set():
    logging.debug('Waiting for stop')
    time.sleep(3)

logging.debug('Stop received')
```

If I don't use the thread and simply call hk.hook(), the code blocks forever without starting the main loop.

```
hk = Hook()
hk.handler = lambda x: handle_hotkeys(x, stop)
hk.hook()
# Blocks here forever, listening to key strokes
```

If I don't start hk_thread with `daemon=True`, the main program will print Stop Recieved and exit after I send Ctrl+F1, but the hotkey thread remains, happily telling me all the keys I press.

If I put something like `hk.unhook_keyboard()` in the handler, again the hotkey thread remains, but now it is no longer listening.

I'm sure there is something fundamental I'm missing here, but I can't seem to figure it out.  Any help would be greatly appreciated.

**Comment by emmatyping** [comment]
First off, I don't see why you are defining a lamda to call handle_hotkeys. That is certainly not correct.

Please read [example_gui.py](https://github.com/ethanhs/pyhooked/blob/master/example_gui.py) for a threaded example.

If that doesn't solve your issue, then I will try your code.

**Comment by msouder** [comment]
I was trying to do a threaded version of your example.py using the logic of example_gui.py (building a Thread with `target=hk.hook`).  PySide won't install for me because I'm using Python 3.5, so I can't run example_gui.py myself just yet.  The lambda was just because I wasn't sure I could modify the event without passing it explicitly to the function.  Turns out it works both ways, but still I got rid of it.  Here is the simplified code:

```
import threading
from pyhooked import Hook, KeyboardEvent
import time

# Setup stop event
stop = threading.Event()

# Setup hot key handler
def handle_hotkeys(args):
    if isinstance(args, KeyboardEvent):
        print(args.key_code)
        if args.current_key == 'F1' and \
                        args.event_type == 'key down' and \
                        'Lcontrol' in args.pressed_key:
            print("Ctrl + F1 was pressed, stopping")
            stop.set()

# Start hot key thread
hk = Hook()
hk.handler = handle_hotkeys
hk_thread = threading.Thread(name='hotkey', target=hk.hook,
                             daemon=False)
hk_thread.start()

# Main loop
while not stop.is_set():
    print('Waiting for stop')
    time.sleep(3)

print('Stop received')
```

With `daemon=False`, the main thread exits after pressing Ctrl+F1, but the hotkey thread keeps going (I think) because hk.hook() blocks and never exits (and I can't figure out a way to get it to exit from the handler function).  With `daemon=True`, the hotkey thread gets killed when the main program exits even though it is blocking on hk.hook().  This is the behavior I want, but according to the docs:

> A thread can be flagged as a “daemon thread”. The significance of this flag is that the entire Python program exits when only daemon threads are left...
> 
> Note Daemon threads are abruptly stopped at shutdown. Their resources (such as open files, database transactions, etc.) may not be released properly. If you want your threads to stop gracefully, make them non-daemonic and use a suitable signalling mechanism such as an Event.

It says that the daemonic threads aren't shut down gracefully so I was wondering if I need to worry about that and/or how am I supposed to be doing this.  In example_gui.py, the thread is started within a class.  Is that the step I'm missing to get it to shutdown gracefully?

**Comment by emmatyping** [comment]
See #25
