### ISSUE TITLE
Licensing issue with hooks.py of pywinauto/UIA - BSD 3-clause license violation

### ISSUE THREAD

**Issue by vasily-v-ryabov** [IronManMark20/pyhooked#15]
Hi @ethanhs , I see pyhooked 0.8 is just some re-factoring (adding more comments, re-ordering some definitions) of [hooks.py](https://github.com/pywinauto/pywinauto/blob/UIA/pywinauto/hooks.py) written by Maxim Samokhvalov mostly from scratch (though all inspirations have been mentioned including pyhooked).

I think it would be polite to mention Maxim's implementation at least. But I see only your own copyright despite BSD 3-clause license requires saving all copyrights of all contributors.

I just want to say referencing each other is mutually useful: it maintains your reputation and shows a good respect to others work.

**Comment by emmatyping** [comment]
Attribution of his work is definitely something I should do, I apologize for not doing so already. Also, I meant to reference pywinauto, I suppose it slipped my mind, I will do that and credit Maxim immediately.

Whose code it is I think is an issue left for lawyers, and I am not a lawyer. As I see it, Maxim's work was based on my original implementation. While it had a different structure, it used much of the same logic especially around the low level handlers. If that is the case, technically the code should be under the LGPL. I suppose I didn't know how much of Maxim's work was from scratch, and thus thought the work would still be under LGPL, but I suppose it does not matter to me if I add the BSD license in the spirit of friendliness, regardless of who did what based on what. :)

I sincerely apologize if my use was disrespectful, as that was not at all my intention. I hope this is a satisfactory solution and we can resolve this confusion.

Please review my changes to the Readme, I hope the changes meet your wishes.

**Comment by vasily-v-ryabov** [comment]
Forget about lawyers, it's not so serious. This is all about good practices which can help to save your reputation. If you know about some similar implementation with noticeable similarity (say between 20% and 50%) that you've inspired of, it's good to mention this inspiration (I did that for pyHook, pyhooked and even your contribution is accurately counted in the list of copyrights in hooks.py).

To be fair I removed all the docstrings and whole-line comments from all three implementations and compared them using simple [string similarity test](https://www.tools4noobs.com/online_tools/string_similarity/):

**pyhooked-0.7** and **hooks.py** are **~40% similar** (I think similarity with pyHook should be approx. the same because Win32 API function names are not changed, some loops and checks are also required in any case), that's why I don't consider it as a derived work, though I mentioned that we inspired of your initial implementation for sure because we had known about it.

**pyhooked-0.8** and **hooks.py** are **~81% similar** (if I was removed some end-of-line comments the similarity would be even higher I'm sure).

This is a visualized comparison of pyhooked-0.8 and hooks.py: https://www.diffnow.com/?report=apjo0
Almost all changes are about re-ordering code parts + imports and function shortcuts re-structuring.

I think I'm quite objective here. So using BSD 3-clause license with respect to all contributors would be the best solution. From my side I can mention that the fork of this code (at some moment) is used in version 0.8 of standalone library `pyhooked` maintained by you. Is it OK? Or you may suggest smoother formulation.

P.S. The files without comments are attached.
[pyhooked_comparison.zip](https://github.com/ethanhs/pyhooked/files/418941/pyhooked_comparison.zip)

**Comment by emmatyping** [comment]
> Forget about lawyers, it's not so serious.

I did not mean to imply lawyers were needed, or it was that serious. I was simply explaining that I am no expert in reading licenses, and "derived work" is one of the vaguest terms I have come across, which I believe has led to a gray area, which has led to this confusion/issue.

> If you know about some similar implementation with noticeable similarity ... th, at you've inspired of, it's good to mention this inspiration

I agree 100%. Any attribution I left out was a serious oversight, and I am trying to cooperate as best I can to fix it.

Your analysis is quite accurate and fair. 0.8 and hooks.py are very similar, as at the time I was working on 0.8, I was under the assumption that hooks.py _was_ a derived work, and thus I could use its code as a basis for 0.8, and license it under the LGPL. At the moment, I really have no idea, so I defer to your judgment. In the interest of respecting Maxim's work, I have already modified [the Readme](https://github.com/ethanhs/pyhooked#license--), and put the 3-clause BSD in, attributing all authors (myself, you, and Maxim). As I understand it, this is what you asked for. Please let me know if you have additional concerns/requests about attribution.

> From my side I can mention that the fork of this code (at some moment) is used in version 0.8 of standalone library pyhooked maintained by you. Is it OK? 

Not only would that be okay, it would be appreciated. :)

**Comment by vasily-v-ryabov** [comment]
OK, I'll review your readme a bit later. Thanks for adding this attribution.
I think you're free to use LGPL for the whole library including examples written by you, but shortened BSDL notification probably should be included into `__init__.py`. Thinking about small pull request further.

**Comment by emmatyping** [comment]
I'm going to close this, as it seems resolved. We can continue discussion in a PR if you feel that is needed.
