### ISSUE TITLE
Support for Mac OSX?

### ISSUE THREAD

**Issue by ivanshen** [IronManMark20/pyhooked#16]
Hi,
Is there any way to implement support for OSX?
Thanks,
Ivan

**Comment by emmatyping** [comment]
This is Windows only. Sorry. It relies on Windows specific libraries to hook into keyboard events. I was able to find [this stackoverflow answer](http://stackoverflow.com/a/11349005/3799589) which seems to have a possible solution. I don't have a Mac, so I'd have no way of testing anything I could write.
