### ISSUE TITLE
Removing a key from "pressed_key" when no longer pressed doesn't work properly

### ISSUE THREAD

**Issue by denniseffing** [IronManMark20/pyhooked#18]
Code used for testing:

```
def handle_events(args):
    if isinstance(args, KeyboardEvent):
    print(args.pressed_key)

hotkey_hook = Hook()
hotkey_hook.handler = handle_events
hotkey_hook.hook()
```

Steps to reproduce: 
1. Start test program
2. Hold any key 
3. Release key

Expected print result:

```
['Lcontrol']
['Lcontrol']
['Lcontrol']
...
```

Actual print result:
![alt text](http://denniseffing.de/screenshots/instantscreen_2016-08-31_23-11-50.png)

**Comment by emmatyping** [comment]
Hm. Could you tell me from what source you installed (PyPi, git, etc)? Also, in your example, are you by chance holding down the <kbd>Ctrl</kbd> key? I am guessing that the code does not check if the key already exists, and just keeps adding it each loop.

**Comment by denniseffing** [comment]
I used pip for installing pyhooked.

And yes, I am holding down the <kbd>CTRL</kbd> key in the example above.
Still, this causes an issue if you compare it with your usage example:

``` python
if args.current_key == 'A' and args.event_type == 'key down' and 'Lcontrol' in args.pressed_key:
    print("Ctrl + A was pressed")
```

If you don't remove the key correctly, `'Lcontrol' in args.pressed_key` will always be true, even if you just press <kbd>A</kbd> after holding **and** releasing <kbd>CTRL</kbd>
