### ISSUE TITLE
Holding down keys

### ISSUE THREAD

**Issue by thesimonho** [IronManMark20/pyhooked#20]
I've managed to get this working for single key presses, but is there an elegant way of handling a situation where a key is held down?

For example I'm using this code to test (running in a while 1 loop in a background thread):

```
if args.current_key == 'A' and args.event_type == 'key down':
    print("A was pressed")
elif args.current_key == 'A' and args.event_type == 'key down' and 'Lcontrol' in args.pressed_key:
    print("Ctrl + A was pressed")
elif args.event_type == 'key down' and 'Lcontrol' in args.pressed_key:
    print("Ctrl was pressed")
elif args.event_type == 'key down' and 'Lshift' in args.pressed_key:
    print("Shift was pressed")
elif args.event_type == 'key down' and 'Lmenu' in args.pressed_key:
    print("Alt was pressed")
```

When a modifier key is held down for more than a few seconds then any other key press does not get picked up. Printing the contents of `args.pressed_key` shows that the list is continually populated by repeated entries of the key pressed down.

I would have thought that this list would be cleared on key up regardless of how long it was held down for? Would that be the cause of my problem?

Or is there a way to check for when a key is held down and to stop trying to register new events until it is released?

**Comment by denniseffing** [comment]
See #18 and #19
The PyPi version is out of date. I already contacted ethanhs via e-mail because of this but he didn't answer yet.

**Comment by emmatyping** [comment]
Sorry. I must have missed that email. I'll post an update to pypi today.

**Comment by emmatyping** [comment]
Okay, I updated pypi. I need to update again to mark the wheels as windows only, but these should work fine.
