### ISSUE TITLE
Mouse events handling

### ISSUE THREAD

**Issue by bduminiuc** [IronManMark20/pyhooked#24]
I changed mouse coordinates and removed keyboard events handling in example.py, so I have the code:

``` python
from pyhooked import Hook, MouseEvent

def handle_events(args):
    if isinstance(args, MouseEvent):
        if args.mouse_x > 0 and args.mouse_y < 500:
            print("Mouse is at ", args.mouse_x, " ", args.mouse_y) 

hk = Hook()  # make a new instance of PyHooked
hk.handler = handle_events  # add a new shortcut ctrl+a, or triggered on mouseover of (300,400)
hk.hook()  # hook into the events, and listen to the presses
```

Next I moved mouse cursor to the left top corner. Then I did some movements and clicks with left and right buttons. So I saw nothing.

Later I tried to add `print(smth)` after isinstance-condition. In that case I saw nothing also.

I use python3.5 and Windows 10

**Comment by emmatyping** [comment]
By default the mouse is not hooked. To get the mouse events you must pass `mouse=True` to the hook call. Hope this helps.
