### ISSUE TITLE
Maintenance mode and moving to keyboard

### ISSUE THREAD

**Issue by emmatyping** [IronManMark20/pyhooked#25]
Dear @all

pyhooked is now two years old (the original version was put into git later than when I wrote it). It has been great to hear of all of the support from the community, and that let what once was a script that I hacked together for my own uses become my first library I shared on Github. It was a great learning experience, but I think I can no longer fulfill my duties as a maintainer for this library as my life gets busier and busier.

That is why I have decided to put pyhooked in maintenance mode. What does this mean to you? If you are just starting to use pyhooked, please consider the excellent [keyboard](https://github.com/boppreh/keyboard). It has a very similar API as the earlier versions of pyhooked. It also adds features such as Linux support and simulating key presses. You might also consider pyhk, or pywinauto's hook module. If you are currently using pyhooked, no need to panic. I will try to fix bugs for the next 3-6 months. I am sure this will be more than enough time to transition to keyboard or whatever alternative you would like to use. If you have concerns about this transition, please don't hesitate to [email me](https://github.com/ethanhs/pyhooked/blob/master/setup.py#L9). 

Finally, I want to thank everyone who helped make pyhooked a great library, your contributions are greatly appreciated! 

Sincerely,
Ethan Smith

**Comment by KeineLimonade** [comment]
Thanks for your effort

**Comment by emmatyping** [comment]
Support has ended. Thanks again all!
